views:
  - name: offering_maturity_insight
    description: This metrices contains analysis around practice
    public: true
    meta:
      tags:   
        - DPDomain.Sales
        - DPUsecase.Practice Impact Insights
        - DPTier.Consumer Aligned
      metric:
        expression: "0 0 1 */2 *"
        timezone: "UTC"
        window: "month"
        excludes: 
           - offerings.id   

    tables:
      - join_path: offerings
        prefix: true

        includes:
          - count
          - id
          - maturity_level
          - updated_at            
      

 